#!/bin/sh
JS=/usr/share/java
CLASSPATH=$JS/kryo.jar:$JS/swing-layout.jar:$JS/dropdabomb.jar:./kryo-2.21.jar:./swing-layout-1.0.4.jar
java -classpath $CLASSPATH lins.me.dropdabomb.Main --server --headless --client
